import { CHUNK_VOLUME } from '../voxel/chunk.ts'

export const GPU_LIGHT_BYTES_PER_VALUE = Uint32Array.BYTES_PER_ELEMENT
export const GPU_LIGHT_BUFFER_BYTE_LENGTH =
  CHUNK_VOLUME * GPU_LIGHT_BYTES_PER_VALUE
export const GPU_LIGHT_MAX_LEVEL = 15
export const GPU_LIGHT_PROPAGATION_ITERATIONS = GPU_LIGHT_MAX_LEVEL + 1
